homepage:
  path: /
  defaults: { _controller: AppBundleDefault:index }

product_overview:
  path: /products
  defaults: { _controller: AppBundle:Product:overview }

product_add:
  path: /products/add 
  methods: [POST]
  defaults: { _controller: AppBundle:Product:add }