AppBundle\Entity\Product:
  type: Entity
  table: product 
  id: 
    id: 
      type: integer 
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: false
      column: name
  sku: 
    type: string
    length: 80
    nullable: true
    column: sku
  price:
    type: integer
    nullable: false
    column: price